config:
    paths:
        'dfnorocronofy/js/app/view/dfn-oro-cronofy-oauth-connect-view': 'bundles/dfnorocronofy/js/app/view/dfn-oro-cronofy-oauth-connect-view.js'
        'dfnorocronofy/js/app/component/dfn-oro-cronofy-oauth-connect-component': 'bundles/dfnorocronofy/js/app/components/dfn-oro-cronofy-oauth-connect-component.js'
        'dfnorocronofy/js/app/view/dfn-oro-cronofy-oauth-disconnect-view': 'bundles/dfnorocronofy/js/app/view/dfn-oro-cronofy-oauth-disconnect-view.js'
        'dfnorocronofy/js/app/component/dfn-oro-cronofy-oauth-disconnect-component': 'bundles/dfnorocronofy/js/app/components/dfn-oro-cronofy-oauth-disconnect-component.js'