system_configuration:
    groups:
        cronofy_settings:
            title: dfn_oro_cronofy.form.cronofy_settings
            icon:  fa-calendar

        cronofy_user_settings:
            title: dfn_oro_cronofy.form.cronofy_settings
            icon:  fa-calendar

        cronofy_api:
            title: dfn_oro_cronofy.form.api_settings

        cronofy_user:
            title: dfn_oro_cronofy.form.calendar_sync

    fields:
        dfn_oro_cronofy.client_id:
            data_type: string
            type: text
            priority: 90
            options:
                label:          dfn_oro_cronofy.form.client_id
                tooltip:        dfn_oro_cronofy.form.tooltip.client_id
                required: true
        dfn_oro_cronofy.client_secret:
            data_type: string
            type: text
            priority: 80
            options:
                label:          dfn_oro_cronofy.form.client_secret
                tooltip:        dfn_oro_cronofy.form.tooltip.client_secret
                required: true
        dfn_oro_cronofy.oauth_connect:
            type: dfn_oro_cronofy_auth
            ui_only: true
            options:
                label: false
                required: false
                resettable: false

    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            cronofy_settings:
                                priority: -10
                                children:
                                    cronofy_api:
                                        priority: 80
                                        children:
                                            - dfn_oro_cronofy.client_id
                                            - dfn_oro_cronofy.client_secret
        organization_configuration:
            platform:
                children:
                    integrations:
                        children:
                            cronofy_settings:
                                priority: -10
                                children:
                                    cronofy_api:
                                        priority: 80
                                        children:
                                            - dfn_oro_cronofy.client_id
                                            - dfn_oro_cronofy.client_secret
        user_configuration:
            platform:
                children:
                    integrations:
                        children:
                            cronofy_user_settings:
                                priority: -10
                                children:
                                    cronofy_user:
                                        priority: 80
                                        children:
                                            - dfn_oro_cronofy.oauth_connect